"""Stage 1 tables (stage1_tables.md) and figure (fig_stage1.png) from stage1_p*.json."""
import json, glob, numpy as np, matplotlib
matplotlib.use('Agg'); import matplotlib.pyplot as plt

FILES = sorted(glob.glob('stage1_p*.json'), key=lambda f: float(f[8:-5]))
DATA = [json.load(open(f)) for f in FILES]
ROWS = ['U-raw', 'U-ZNE exp', 'U-ZNE cum2', 'E-raw', 'E-par', 'E-PS', 'E-ORP', 'E-soft', 'E-geo', 'E-ext', 'E-PS+ZNE exp', 'E-PS+ZNE cum2', 'E-PS+PEC']
SCHED = ['1', '2', 'end']
def fmt(n): return '∞' if not np.isfinite(n) else (f'{n/1e6:.1f}M' if n >= 1e6 else f'{n/1e3:.0f}k' if n >= 1e3 else f'{n/1e3:.1f}k')

L = ['# Stage 1 tables: shots for RMSE ≤ 0.02 (infinite-shot bias)', '',
     'Generated by `make_stage1_report.py` from `stage1_p*.json`. Shots are the total before post-selection (split equally over gains); ∞ = bias exceeds 0.02. '
     'Exact (density-matrix) infinite-shot values for U-*, E-raw, E-par, E-PS, E-ext, E-PS+ZNE, E-PS+PEC; trajectory pool (10⁶ shots) for E-ORP, E-soft, E-geo.', '']
for D in DATA:
    for obs in ('Z0', 'ZZ'):
        for sc in SCHED:
            cf = sorted([v for v in D['configs'].values() if v['sched'] == sc], key=lambda v: v['steps'])
            if not cf: continue
            L += [f"## p = {100*D['p']:.1f}%, observable {'⟨Z̄₀⟩' if obs=='Z0' else '⟨Z̄₀Z̄₁⟩'}, syndrome rounds: {'every step' if sc=='1' else 'every 2 steps' if sc=='2' else 'one at the end'}", '',
                  '| protocol | ' + ' | '.join(f"{v['steps']} steps" for v in cf) + ' |', '|---|' + '---|' * len(cf)]
            L.append('| ideal | ' + ' | '.join(f"{v['obs'][obs]['ideal']:+.3f}" for v in cf) + ' |')
            L.append('| PS acceptance | ' + ' | '.join(f"{v['obs'][obs]['acc_ps']:.2f}" for v in cf) + ' |')
            L.append('| CX enc / unenc | ' + ' | '.join(f"{v['cx_enc']} / {v['cx_une']}" for v in cf) + ' |')
            L.append('| Λ_u (harmful undetected) / Λ_d | ' + ' | '.join(f"{v['Lambda_u']:.3f} / {v['Lambda_d']:.3f}" for v in cf) + ' |')
            for r in ROWS:
                L.append(f'| {r} | ' + ' | '.join(f"{fmt(v['obs'][obs]['est'][r]['nreq'])} ({v['obs'][obs]['est'][r]['bias']:+.3f})" for v in cf) + ' |')
            L.append('')
open('stage1_tables.md', 'w').write('\n'.join(L))

SER = [('U-ZNE exp', 'unencoded + ZNE exp', '#2a78d6', '-', 'o'), ('U-ZNE cum2', 'unencoded + ZNE 2nd cumulant', '#eb6834', '-', 's'),
       ('E-ORP', 'encoded + ORP', '#1baf7a', '-', '^'), ('E-PS+ZNE exp', 'encoded PS + ZNE exp', '#eda100', '-', 'D'),
       ('E-PS', 'encoded full PS', '#e87ba4', '-', 'v'), ('E-PS+PEC', 'encoded PS + PEC, exact model (ref.)', '#52514e', '--', 'x')]
nP = len(DATA)
fig, ax = plt.subplots(2, nP * 2, figsize=(4.0 * nP * 2, 7.0), squeeze=False)
for i, D in enumerate(DATA):
    for j, sc in enumerate(('1', 'end')):
        col = 2 * i + j; cf = sorted([v for v in D['configs'].values() if v['sched'] == sc], key=lambda v: v['steps'])
        if not cf: continue
        x = [v['steps'] for v in cf]
        for si, (k, lab, cl, ls, mk) in enumerate(SER):
            b = [abs(v['obs']['Z0']['est'][k]['bias']) for v in cf]; n = np.array([v['obs']['Z0']['est'][k]['nreq'] for v in cf])
            ax[0, col].plot(x, b, ls, color=cl, marker=mk, ms=5, lw=2, label=lab)
            fin = np.isfinite(n); ax[1, col].plot(x, np.where(fin, n, np.nan), ls, color=cl, marker=mk, ms=5, lw=2)
            if (~fin).any(): ax[1, col].plot(np.array(x)[~fin], [3e7 / 2.2 ** si] * (~fin).sum(), 'x', color=cl, ms=8, mew=2)
        ax[0, col].axhline(0.02, color='#999', lw=1, ls=':'); ax[0, col].set_yscale('log'); ax[0, col].set_ylim(1e-4, 0.5)
        ax[1, col].set_yscale('log'); ax[1, col].set_ylim(3e2, 6e7); ax[1, col].set_xlabel('Trotter steps')
        ax[0, col].set_title(f"p = {100*D['p']:.1f}%, syndrome {'every step' if sc=='1' else 'at end'}", fontsize=10)
        for a in ax[:, col]: a.grid(alpha=0.25, lw=0.6); a.spines[['top', 'right']].set_visible(False)
ax[0, 0].set_ylabel('|bias| of ⟨Z̄₀⟩'); ax[1, 0].set_ylabel('shots for RMSE ≤ 0.02\n(× at top: bias > 0.02)')
fig.legend(*ax[0, 0].get_legend_handles_labels(), loc='lower center', ncol=6, fontsize=8.5, frameon=False)
fig.tight_layout(rect=(0, 0.06, 1, 1)); fig.savefig('fig_stage1.png', dpi=140)
print('\n'.join(L[:40]))
