"""Tables (hh_tables.md) and figure (fig_hh.png) from hh_p*.json."""
import json, glob, numpy as np, matplotlib
matplotlib.use('Agg'); import matplotlib.pyplot as plt

FILES = sorted(glob.glob('hh_p*.json'), key=lambda f: -float(f[4:-5]))
DATA = [json.load(open(f)) for f in FILES]
ROWS = ['raw', 'ZNE exp', 'ZNE cum2', 'SV+ZNE exp', 'SV+ZNE cum2',
        'PS[M]', 'PS+SV[M]', 'ext r[M]', 'ext r+SV[M]', 'PS+ZNE exp[M]', 'PS+SV+ZNE exp[M]', 'PS+SV+ZNE cum2[M]', 'PEC oracle[M]', 'PEC+SV oracle[M]',
        'PS+SV[MP]', 'ext r+SV[MP]', 'PS+SV+ZNE exp[MP]', 'PEC+SV oracle[MP]']
def fmt_n(n): return '∞' if not np.isfinite(n) else (f'{n/1e6:.1f}M' if n >= 1e6 else f'{n/1e3:.0f}k' if n >= 1e3 else f'{n/1e3:.1f}k')

lines = ['# Heavy-hex plaquette: shots for RMSE ≤ 0.02 (bias in parentheses)', '',
         'Generated by `make_hh_report.py` from `hh_p*.json`. Shots are the total before post-selection (split equally over gains); '
         '∞ means the infinite-shot bias exceeds 0.02. [M] = mediator flags only, [MP] = mediators + peripheral checks, SV = parity post-selection.', '']
for D in DATA:
    ds = sorted(D['depths'], key=int)
    lines += [f"## p = q = {100*D['p']:.1f}%", '', '| protocol | ' + ' | '.join(f'd={d}' for d in ds) + ' |', '|---|' + '---|' * len(ds)]
    lines.append('| ideal m_x | ' + ' | '.join(f"{D['depths'][d]['ideal']:+.3f}" for d in ds) + ' |')
    lines.append('| acceptance PS [M] / [MP] | ' + ' | '.join(f"{D['depths'][d]['alpha']['M']:.2f} / {D['depths'][d]['alpha']['MP']:.2f}" for d in ds) + ' |')
    for r in ROWS:
        cells = []
        for d in ds:
            e = D['depths'][d]['est'][r]; cells.append(f"{fmt_n(e['nreq'])} ({e['bias']:+.3f})")
        lines.append(f'| {r} | ' + ' | '.join(cells) + ' |')
    lines.append('')
open('hh_tables.md', 'w').write('\n'.join(lines))

# figure: |bias| (top) and shots for RMSE <= 0.02 (bottom), one column per noise level
SER = [('ZNE exp', 'ZNE exponential', '#2a78d6', '-', 'o'),
       ('ZNE cum2', 'ZNE 2nd cumulant', '#eb6834', '-', 's'),
       ('ext r[M]', 'detection ext. (structural r), mediator flags', '#1baf7a', '-', '^'),
       ('PS+ZNE exp[M]', 'mediator PS + ZNE exp', '#eda100', '-', 'D'),
       ('PEC oracle[M]', 'mediator PS + PEC, exact model (reference)', '#52514e', '--', 'v')]
fig, ax = plt.subplots(2, len(DATA), figsize=(4.2 * len(DATA), 7.0), sharex='col', squeeze=False)
for c, D in enumerate(DATA):
    ds = sorted(D['depths'], key=int); x = [int(d) for d in ds]; top = 0
    for si, (key, lab, col, ls, mk) in enumerate(SER):
        b = [abs(D['depths'][d]['est'][key]['bias']) for d in ds]; n = np.array([D['depths'][d]['est'][key]['nreq'] for d in ds])
        ax[0, c].plot(x, b, ls, color=col, marker=mk, ms=5, lw=2, label=lab)
        fin = np.isfinite(n); ax[1, c].plot(x, np.where(fin, n, np.nan), ls, color=col, marker=mk, ms=5, lw=2)   # gaps where unreachable
        top = max(top, n[fin].max() if fin.any() else 0)
        if (~fin).any(): ax[1, c].plot(np.array(x)[~fin], [3e7 / 2.2 ** si] * (~fin).sum(), 'x', color=col, ms=8, mew=2)
    ax[0, c].axhline(0.02, color='#999', lw=1, ls=':'); ax[0, c].set_yscale('log'); ax[0, c].set_ylim(1e-4, 0.3)
    ax[1, c].set_yscale('log'); ax[1, c].set_ylim(3e2, 6e7); ax[1, c].set_xlabel('Trotter depth d')
    ax[0, c].set_title(f"p = q = {100*D['p']:.1f}%")
    for a in ax[:, c]: a.grid(alpha=0.25, lw=0.6); a.spines[['top', 'right']].set_visible(False)
ax[0, 0].set_ylabel('|bias| of $m_x$ (infinite shots)'); ax[1, 0].set_ylabel('shots for RMSE ≤ 0.02\n(× at top: bias > 0.02)')
fig.legend(*ax[0, 0].get_legend_handles_labels(), loc='lower center', ncol=3, fontsize=8.5, frameon=False)
fig.tight_layout(rect=(0, 0.08, 1, 1)); fig.savefig('fig_hh.png', dpi=150)
print('\n'.join(lines))
